apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-pagina-web
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  storageClassName: "standard"
  hostPath:
    path: "/home/docker/pagina-web"
  persistentVolumeReclaimPolicy: Retain

