apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-pagina-web
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: "standard"
  resources:
    requests:
      storage: 1Gi


      